import { fontFamily } from "./fonts";

export const baseStyle = {
  direction: "ltr",
  fillStyle: "#fff",
  // filter: 'grayscale(.9)',
  filter: "none",
  font: "16px " + fontFamily,
  globalAlpha: 1,
  globalCompositeOperation: "source-over",
  // imageSmoothingEnabled: true,
  // imageSmoothingQuality: 'low',
  imageSmoothingEnabled: false,
  lineCap: "butt",
  lineDashOffset: 0,
  lineJoin: "miter",
  lineWidth: 1,
  miterLimit: 10,
  shadowBlur: 0,
  shadowColor: "rgba(0, 0, 0, 0)",
  shadowOffsetX: 0,
  shadowOffsetY: 0,
  strokeStyle: "white",
  textAlign: "start",
  // textBaseline: "alphabetic",
  // textBaseline: "middle",
  textBaseline: "top",
};
