version: '1.0'
name: pipeline-20220103
displayName: pipeline-20220103
triggers:
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-f99da07f
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        commands:
          - npm install && rm -rf ./dist && npm run build
permissions:
  - role: admin
    members: []
